# Phase 2 Array
---

In [1]:
import numpy as np

## NumPy Array Operation 
---


- Basic Slicing


In [12]:
arr = np.arange(11)
print("Orginal Array:\n",arr)
print("Basic Slicing:\n",arr[2:6])
print("Negetive Index:",arr[-0])
print("Negetive Index:",arr[-5])
print("Negetive Index:",arr[-4])

print("\n\n")

arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Orginal Array:\n",arr1)
print("Basic Slicing :\n",arr1[3:8])
print("Negetive Index:",arr[-4])
print("Negetive Index:",arr[-3])
print("Negetive Index:",arr[-2])

Orginal Array:
 [ 0  1  2  3  4  5  6  7  8  9 10]
Basic Slicing:
 [2 3 4 5]
Negetive Index: 0
Negetive Index: 6
Negetive Index: 7



Orginal Array:
 [ 1  2  3  4  5  6  7  8  9 10]
Basic Slicing :
 [4 5 6 7 8]
Negetive Index: 7
Negetive Index: 8
Negetive Index: 9


In [8]:
print("With Step Or Slice",arr[1:10:3]) # in this 1:10:3 => 1 is start index, 10 is stop index, 3 is the index that is picked after first  index
print("With Step Or Slice",arr1[1:5:2])

With Step Or Slice [1 4 7]
With Step Or Slice [2 4]


## 2D Array

In [15]:
arr2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Specific Element :",arr2d[1,1])
print("Specific Element :",arr2d[0,0])
print("Specific Element :",arr2d[0,2])


Specific Element : 5
Specific Element : 1
Specific Element : 3


---
## Sorting Array

In [16]:
unsorted = np.array([3,2,4,4,5,6,2,5,6,7,32,4,56,2,455,67,24])
print(unsorted)
print("sorted array",np.sort(unsorted))

[  3   2   4   4   5   6   2   5   6   7  32   4  56   2 455  67  24]
sorted array [  2   2   2   3   4   4   4   5   5   6   6   7  24  32  56  67 455]


---
### Sorting 2D Array


In [20]:
unsorted2d = np.array([[1,2],[3,1],[2,4],[5,2]])
print("Sorting 2D By Column \n",np.sort(unsorted2d,axis=0))
print("Sorting 2D By Row \n",np.sort(unsorted2d,axis=1))


Sorting 2D By Column 
 [[1 1]
 [2 2]
 [3 2]
 [5 4]]
Sorting 2D By Row 
 [[1 2]
 [1 3]
 [2 4]
 [2 5]]
