# Phase 2 Array
---

In [4]:
import numpy as np

## NumPy Array Operation 
---


- Basic Slicing


In [5]:
arr = np.arange(11)
print("Orginal Array:\n",arr)
print("Basic Slicing:\n",arr[2:6])
print("Negetive Index:",arr[-0])
print("Negetive Index:",arr[-5])
print("Negetive Index:",arr[-4])

print("\n\n")

arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Orginal Array:\n",arr1)
print("Basic Slicing :\n",arr1[3:8])
print("Negetive Index:",arr[-4])
print("Negetive Index:",arr[-3])
print("Negetive Index:",arr[-2])

Orginal Array:
 [ 0  1  2  3  4  5  6  7  8  9 10]
Basic Slicing:
 [2 3 4 5]
Negetive Index: 0
Negetive Index: 6
Negetive Index: 7



Orginal Array:
 [ 1  2  3  4  5  6  7  8  9 10]
Basic Slicing :
 [4 5 6 7 8]
Negetive Index: 7
Negetive Index: 8
Negetive Index: 9


In [6]:
print("With Step Or Slice",arr[1:10:3]) # in this 1:10:3 => 1 is start index, 10 is stop index, 3 is the index that is picked after first  index
print("With Step Or Slice",arr1[1:5:2])

With Step Or Slice [1 4 7]
With Step Or Slice [2 4]


---
## 2D Array

In [7]:
arr2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Specific Element :",arr2d[1,1])
print("Specific Element :",arr2d[0,0])
print("Specific Element :",arr2d[0,2])

print("Selct  row       :",arr2d[2])
print("selected Column  :",arr2d[:,2])

arr2dmax = arr2d.max()
print("Maximim Value :",arr2dmax)


Specific Element : 5
Specific Element : 1
Specific Element : 3
Selct  row       : [7 8 9]
selected Column  : [3 6 9]
Maximim Value : 9


---
## Sorting Array

In [8]:
unsorted = np.array([3,2,4,4,5,6,2,5,6,7,32,4,56,2,455,67,24])
print(unsorted)
print("sorted array",np.sort(unsorted))

[  3   2   4   4   5   6   2   5   6   7  32   4  56   2 455  67  24]
sorted array [  2   2   2   3   4   4   4   5   5   6   6   7  24  32  56  67 455]


---
### Sorting 2D Array


In [9]:
unsorted2d = np.array([[1,2],[3,1],[2,4],[5,2]])
print("Sorting 2D By Column \n",np.sort(unsorted2d,axis=0))
print("Sorting 2D By Row \n",np.sort(unsorted2d,axis=1))


print()


Sorting 2D By Column 
 [[1 1]
 [2 2]
 [3 2]
 [5 4]]
Sorting 2D By Row 
 [[1 2]
 [1 3]
 [2 4]
 [2 5]]



---
## Filtering Array

In [10]:
Numbers = np.arange(1,51)

evenNO = Numbers[Numbers % 2 == 0]
oddNo = Numbers[Numbers % 2 == 1]

print("Even No:\n",evenNO)
print("Odd  No:\n",oddNo)


Even No:
 [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
Odd  No:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


### Filter With Masks

In [11]:
mask =  (Numbers > 20) & (Numbers <= 40)
print("Filter Using Masks",Numbers[mask])

Filter Using Masks [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


---
# Fancy Indexing Vs np.where

In [15]:
indices = [1,5,3,24]
print(Numbers[indices])


where_result = np.where((Numbers < 20)& (Numbers > 5))
print("NP where:\n",where_result)

print("same same but different",Numbers[where_result])

[ 2  6  4 25]
NP where:
 (array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18]),)
same same but different [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]


---
### Conditional Array


In [ ]:
num = np.arange(0,21)
print("Original array     ",num)
conditionalArr = np.where((num > 10)&(num<20),num*2,num)
print("multiply 2 after 10",conditionalArr)

Original array      [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
multiply 2 after 10 [ 0  1  2  3  4  5  6  7  8  9 10 22 24 26 28 30 32 34 36 38 20]


---
# Adding And Removing Data from Array

In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

adding = np.concatenate((arr1,arr2))
adding1 = np.concatenate((arr2,arr1))
print(adding)
print(adding1)

[1 2 3 4 5 6]
[4 5 6 1 2 3]


### Array Compatibility 

In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8])

print("Compatibilty Shapes => ", a.shape == b.shape)
print("Compatibilty Shapes => ", b.shape == c.shape)

Compatibilty Shapes =>  True
Compatibilty Shapes =>  False


### Array Row Add


In [ ]:
with_row = np.vstack((a,b))
with_column = np.hstack((a,b))


print(with_row)
print(with_column)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [36]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
deleted  =  np.delete(arr,3)
print(deleted)
print(arr)

[ 1  2  3  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
