# Creating Array And List In python

In [10]:
import numpy as np

In [11]:

# creating list

py_list = [1,2,3,4]
print(py_list)

# # Multiplication Of List

# print("Multiplication ",py_list * 2)

# creating array using numpy

py_array = np.array([1,2,3,4])
print(py_array)

# # Multiplication Of Array

# print("Multiplication ",py_array * 2)

# Differnece between list and array

print("list",py_list,":Multiplication(2)=",py_list*2,"\nArray",py_array,":multplication(2)=",py_array*2)

[1, 2, 3, 4]
[1 2 3 4]
list [1, 2, 3, 4] :Multiplication(2)= [1, 2, 3, 4, 1, 2, 3, 4] 
Array [1 2 3 4] :multplication(2)= [2 4 6 8]


In [13]:
zeros  = np.zeros((5,5))
print("Zeros in Nummpy:\n",zeros)

Zeros in Nummpy:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
ones = np.ones((3,4))
print("Ones In NumPy: \n",ones)

Ones In NumPy: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
full = np.full((2,2),4)
print("Full Array :\n",full)

Full Array :
 [[4 4]
 [4 4]]


In [ ]:
random = np.random.random((3,4))
print("Random Array :\n",random)

Random Array :
 [[0.94622946 0.94990483 0.4504915  0.14750274]
 [0.62742488 0.90633186 0.31886598 0.61613461]
 [0.51638957 0.95608655 0.79446383 0.83000455]]


In [22]:
sequence = np.arange(0,11,2)
print("Sequencce Array:\n",sequence)
sequence = np.arange(0,100)
print("Sequencce Array:\n",sequence)

Sequencce Array:
 [ 0  2  4  6  8 10]
Sequencce Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# Vector , Matrix & Tensor
---

# Vector 
---

In [27]:
vector = np.array([1,2,3,4,5,6])
print("Vector :\n",vector)

Vector :
 [1 2 3 4 5 6]


# Matrix
---

In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("Matrix :\n",matrix)

Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Tensor
---

In [26]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor :\n",tensor)

Tensor :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Properties Of Array
---

In [29]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print("Shape Of Array:",arr.shape)
print("Dimention Of Array:",arr.ndim)
print("Size of Array:",arr.size)
print("Datatype Of Array:",arr.dtype)

Shape Of Array: (2, 3)
Dimention Of Array: 2
Size of Array: 6
Datatype Of Array: int64


# Reshaping Array


In [33]:
arr = np.arange(12)
print("Original Array:\n",arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array:\n",reshaped)

Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Flatened Array From REshaped Array
---

In [34]:
flatened = reshaped.flatten()
print("Flatten array\n", flatened)

Flatten array
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Raveled array (Returns the original or view instead of copy array..)
---

In [35]:
raveled = reshaped.ravel()
print("Raveled Array :\n",raveled)

Raveled Array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
#Transpose array
transpose = reshaped.T
print("Transpose Array:\n",transpose)

Transpose Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
