# Pracice Using Daa
---

In [4]:
import numpy as np
import matplotlib.pyplot as pl


In [ ]:
# Daa srucure: [resauran_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
[1, 150000, 180000, 220000, 250000],
[2, 120000, 140000, 160000, 190000], 
[3, 200000, 230000, 260000, 300000],
[4, 180000, 210000, 240000, 270000],
[5, 160000, 185000, 205000, 230000],
[6, 170000, 195000, 225000, 260000],
[7, 130000, 150000, 175000, 200000], 
[8, 190000, 220000, 245000, 280000],
[9, 155000, 180000, 210000, 235000],
[10, 165000, 190000, 215000, 240000],
[11, 175000, 200000, 230000, 255000],
[12, 140000, 165000, 190000, 215000], 
[13, 205000, 235000, 260000, 290000],
[14, 185000, 215000, 245000, 270000],
[15, 170000, 195000, 220000, 245000],
[16, 160000, 185000, 210000, 235000],
[17, 145000, 170000, 195000, 220000], 
[18, 195000, 225000, 250000, 275000],
[19, 180000, 205000, 230000, 260000],
[20, 175000, 200000, 225000, 250000],
[21, 150000, 180000, 220000, 250000],
[22, 120000, 140000, 160000, 190000], 
[23, 200000, 230000, 260000, 300000],
[24, 180000, 210000, 240000, 270000],
[25, 160000, 185000, 205000, 230000],
[26, 170000, 195000, 225000, 260000],
[27, 130000, 150000, 175000, 200000], 
[28, 190000, 220000, 245000, 280000],
[29, 155000, 180000, 210000, 235000],
[30, 165000, 190000, 215000, 240000],
[31, 175000, 200000, 230000, 255000],
[32, 140000, 165000, 190000, 215000], 
[33, 205000, 235000, 260000, 290000],
[34, 185000, 215000, 245000, 270000],
[35, 170000, 195000, 220000, 245000],
[36, 160000, 185000, 210000, 235000],
[37, 145000, 170000, 195000, 220000], 
[38, 195000, 225000, 250000, 275000],
[39, 180000, 205000, 230000, 260000],
[40, 175000, 200000, 225000, 250000],
[41, 150000, 180000, 220000, 250000],
[42, 120000, 140000, 160000, 190000], 
[43, 200000, 230000, 260000, 300000],
[44, 180000, 210000, 240000, 270000],
[45, 160000, 185000, 205000, 230000],
[46, 170000, 195000, 225000, 260000],
[47, 130000, 150000, 175000, 200000], 
[48, 190000, 220000, 245000, 280000],
[49, 155000, 180000, 210000, 235000],
[50, 165000, 190000, 215000, 240000],
[51, 175000, 200000, 230000, 255000],
[52, 140000, 165000, 190000, 215000], 
[53, 205000, 235000, 260000, 290000],
[54, 185000, 215000, 245000, 270000],
[55, 170000, 195000, 220000, 245000],
[56, 160000, 185000, 210000, 235000],
[57, 145000, 170000, 195000, 220000], 
[58, 195000, 225000, 250000, 275000],
[59, 180000, 205000, 230000, 260000],
[60, 175000, 200000, 225000, 250000],
[61, 150000, 180000, 220000, 250000],
[62, 120000, 140000, 160000, 190000], 
[63, 200000, 230000, 260000, 300000],
[64, 180000, 210000, 240000, 270000],
[65, 160000, 185000, 205000, 230000],
[66, 170000, 195000, 225000, 260000],
[67, 130000, 150000, 175000, 200000], 
[68, 190000, 220000, 245000, 280000],
[69, 155000, 180000, 210000, 235000],
[70, 165000, 190000, 215000, 240000],
[71, 175000, 200000, 230000, 255000],
[72, 140000, 165000, 190000, 215000], 
[73, 205000, 235000, 260000, 290000],
[74, 185000, 215000, 245000, 270000],
[75, 170000, 195000, 220000, 245000],
[76, 160000, 185000, 210000, 235000],
[77, 145000, 170000, 195000, 220000], 
[78, 195000, 225000, 250000, 275000],
[79, 180000, 205000, 230000, 260000],
[80, 175000, 200000, 225000, 250000],
[81, 150000, 180000, 220000, 250000],
[82, 120000, 140000, 160000, 190000], 
[83, 200000, 230000, 260000, 300000],
[84, 180000, 210000, 240000, 270000],
[85, 160000, 185000, 205000, 230000],
[86, 170000, 195000, 225000, 260000],
[87, 130000, 150000, 175000, 200000], 
[88, 190000, 220000, 245000, 280000],
[89, 155000, 180000, 210000, 235000],
[90, 165000, 190000, 215000, 240000],
[91, 175000, 200000, 230000, 255000],
[92, 140000, 165000, 190000, 215000], 
[93, 205000, 235000, 260000, 290000],
[94, 185000, 215000, 245000, 270000],
[95, 170000, 195000, 220000, 245000],
[96, 160000, 185000, 210000, 235000],
[97, 145000, 170000, 195000, 220000], 
[98, 195000, 225000, 250000, 275000],
[99, 180000, 205000, 230000, 260000],
[100, 175000, 200000, 225000, 250000]
])

print("  ====  Zomato Sales Analysis  ====  \n")
print("Shape Of DATA\n",sales_data.shape)


print("\nSample Data From 1 to 10\n",sales_data[:10])
# print("\n removes the first column from everydata \n",sales_data[:,1:])##removes the first column





  ====  Zomato Sales Analysis  ====  

Shape Of DATA
 (100, 5)

Sample Data From 1 to 10
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]
 [     6 170000 195000 225000 260000]
 [     7 130000 150000 175000 200000]
 [     8 190000 220000 245000 280000]
 [     9 155000 180000 210000 235000]
 [    10 165000 190000 215000 240000]]


---
# Total Sales Per Year
---

In [47]:
total = np.sum(sales_data[:,1:],axis=0)
print("Total Sales of year wise\n" \
"  2021    2022    2023    2024\n",total)
print("\n")

total1 = np.sum(sales_data[:,1:],axis=1)
for i in range(0,100):
    print("ID wise Total Data::",i,total1[i])

print("\n")
print("ID Wise Total data..\n",total1)

print("\n")

totalrow = np.sum(total)
print("TOTAL sum of Year ",totalrow)

print("\n")

totalcolumn = np.sum(total1)
print("TOTAL sum of Year ",totalcolumn)


Total Sales of year wise
  2021    2022    2023    2024
 [16750000 19375000 22050000 24850000]


ID wise Total Data:: 0 800000
ID wise Total Data:: 1 610000
ID wise Total Data:: 2 990000
ID wise Total Data:: 3 900000
ID wise Total Data:: 4 780000
ID wise Total Data:: 5 850000
ID wise Total Data:: 6 655000
ID wise Total Data:: 7 935000
ID wise Total Data:: 8 780000
ID wise Total Data:: 9 810000
ID wise Total Data:: 10 860000
ID wise Total Data:: 11 710000
ID wise Total Data:: 12 990000
ID wise Total Data:: 13 915000
ID wise Total Data:: 14 830000
ID wise Total Data:: 15 790000
ID wise Total Data:: 16 730000
ID wise Total Data:: 17 945000
ID wise Total Data:: 18 875000
ID wise Total Data:: 19 850000
ID wise Total Data:: 20 800000
ID wise Total Data:: 21 610000
ID wise Total Data:: 22 990000
ID wise Total Data:: 23 900000
ID wise Total Data:: 24 780000
ID wise Total Data:: 25 850000
ID wise Total Data:: 26 655000
ID wise Total Data:: 27 935000
ID wise Total Data:: 28 780000
ID wise Total 

---
## Minimum Sales In Sales DATA
---

In [75]:
minSale = np.min(sales_data[:,1:],axis=0)
for i in range(0,4):
    a = 2021
    print("Maximum sales per year:",(a+i),"=>",minSale[i])


print("\n\n")

minSale = np.min(sales_data[:,1:],axis=1)
for i in range (0,100):
    a=1
    print("Minimum Data ID wise::",(a+i),"=>",minSale[i])





Maximum sales per year: 2021 => 120000
Maximum sales per year: 2022 => 140000
Maximum sales per year: 2023 => 160000
Maximum sales per year: 2024 => 190000



Minimum Data ID wise:: 1 => 150000
Minimum Data ID wise:: 2 => 120000
Minimum Data ID wise:: 3 => 200000
Minimum Data ID wise:: 4 => 180000
Minimum Data ID wise:: 5 => 160000
Minimum Data ID wise:: 6 => 170000
Minimum Data ID wise:: 7 => 130000
Minimum Data ID wise:: 8 => 190000
Minimum Data ID wise:: 9 => 155000
Minimum Data ID wise:: 10 => 165000
Minimum Data ID wise:: 11 => 175000
Minimum Data ID wise:: 12 => 140000
Minimum Data ID wise:: 13 => 205000
Minimum Data ID wise:: 14 => 185000
Minimum Data ID wise:: 15 => 170000
Minimum Data ID wise:: 16 => 160000
Minimum Data ID wise:: 17 => 145000
Minimum Data ID wise:: 18 => 195000
Minimum Data ID wise:: 19 => 180000
Minimum Data ID wise:: 20 => 175000
Minimum Data ID wise:: 21 => 150000
Minimum Data ID wise:: 22 => 120000
Minimum Data ID wise:: 23 => 200000
Minimum Data ID wise::

---
# MAXIMUM SALES PER YEAR
---

In [72]:
maxiSale = np.max(sales_data[:,1:],axis=0)
for i in range(0,4):
    a = 2021
    print("Maximum sales per year:",(a+i),"=>",maxiSale[i])

print("\n\n")


maxiSaleID = np.max(sales_data[:,1:],axis=1)
for i in range (0,100):
    a=1
    print("Maximum Sales ID wise::",(a+i),"=>",maxiSaleID[i])


Maximum sales per year: 2021 => 205000
Maximum sales per year: 2022 => 235000
Maximum sales per year: 2023 => 260000
Maximum sales per year: 2024 => 300000



Maximum Sales ID wise:: 1 => 250000
Maximum Sales ID wise:: 2 => 190000
Maximum Sales ID wise:: 3 => 300000
Maximum Sales ID wise:: 4 => 270000
Maximum Sales ID wise:: 5 => 230000
Maximum Sales ID wise:: 6 => 260000
Maximum Sales ID wise:: 7 => 200000
Maximum Sales ID wise:: 8 => 280000
Maximum Sales ID wise:: 9 => 235000
Maximum Sales ID wise:: 10 => 240000
Maximum Sales ID wise:: 11 => 255000
Maximum Sales ID wise:: 12 => 215000
Maximum Sales ID wise:: 13 => 290000
Maximum Sales ID wise:: 14 => 270000
Maximum Sales ID wise:: 15 => 245000
Maximum Sales ID wise:: 16 => 235000
Maximum Sales ID wise:: 17 => 220000
Maximum Sales ID wise:: 18 => 275000
Maximum Sales ID wise:: 19 => 260000
Maximum Sales ID wise:: 20 => 250000
Maximum Sales ID wise:: 21 => 250000
Maximum Sales ID wise:: 22 => 190000
Maximum Sales ID wise:: 23 => 300000

---
# Average Sales
---

In [71]:
avgSale = np.mean(sales_data[:,1:],axis=0)
for  i in range(0,4):
    a = 2021
    print("Average Sale By Year:",(a+i),"=>",avgSale[i])

print("\n\n")

avgSaleID = np.mean(sales_data[:,1:],axis=1)
for i in range(0,100):
    a=1
    print("Average Sale By Id:",(a+i),"=>",avgSaleID[i])

maxi = np.max(avgSaleID)
print(maxi)


Average Sale By Year: 2021 => 167500.0
Average Sale By Year: 2022 => 193750.0
Average Sale By Year: 2023 => 220500.0
Average Sale By Year: 2024 => 248500.0



Average Sale By Id: 1 => 200000.0
Average Sale By Id: 2 => 152500.0
Average Sale By Id: 3 => 247500.0
Average Sale By Id: 4 => 225000.0
Average Sale By Id: 5 => 195000.0
Average Sale By Id: 6 => 212500.0
Average Sale By Id: 7 => 163750.0
Average Sale By Id: 8 => 233750.0
Average Sale By Id: 9 => 195000.0
Average Sale By Id: 10 => 202500.0
Average Sale By Id: 11 => 215000.0
Average Sale By Id: 12 => 177500.0
Average Sale By Id: 13 => 247500.0
Average Sale By Id: 14 => 228750.0
Average Sale By Id: 15 => 207500.0
Average Sale By Id: 16 => 197500.0
Average Sale By Id: 17 => 182500.0
Average Sale By Id: 18 => 236250.0
Average Sale By Id: 19 => 218750.0
Average Sale By Id: 20 => 212500.0
Average Sale By Id: 21 => 200000.0
Average Sale By Id: 22 => 152500.0
Average Sale By Id: 23 => 247500.0
Average Sale By Id: 24 => 225000.0
Average Sa